version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Download counter
          command: |
            bash <(curl -s https://gist.githubusercontent.com/rauldipeas/94f6f087165786bf671f2bf4242259b4/raw/71a2bc39dadf92cbd158f0b3a3cac584f9826338/github-downloads-count.sh)
            git clone https://github.com/rauldipeas/radix-website;cd radix-website
            cp ../download-counter.log website/download-counter.log/download-counter.log
            git config --global user.email "rauldipeas@mail.com";git config --global user.name "Raul Dipeas"
            git add .; git commit -m "CircleCI Auto Build";git push -u origin master
